---
- apt: pkg=$item state=latest install_recommends=no
  with_items:
  - python-pycurl
- apt_repository: repo='ppa:git-core'
- apt_key: url=https://get.docker.io/gpg state=present
- apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present
- apt: update_cache=yes cache_valid_time=7200
- apt: pkg=$item state=latest install_recommends=no
  with_items:
  - lxc-docker
  - git-core  
  - tmux
  - htop
  - mc  
  - vim
  - curl
- name: ENV | zookeepers
  template: src=zookeeper.sh.j2 dest=/etc/profile.d/zookeeper.sh mode=755
