---
- apt: pkg=$item state=latest install_recommends=no
  with_items:
  - python-pycurl
- apt_repository: repo='ppa:git-core'
- apt_repository: repo='ppa:webupd8team/java'
- apt_repository: repo='ppa:brightbox/ruby-ng'
- apt_repository: repo='ppa:chris-lea/node.js'
- apt: update_cache=yes cache_valid_time=7200
- apt: pkg=$item state=latest install_recommends=no
  with_items:
  - git-core  
  - tmux
  - htop
  - mc  
  - vim
  - curl
  - build-essential
  - gawk
  - libyaml-dev
  - libsqlite3-dev
  - sqlite3
  - libffi-dev
- name: Accept the license for Oracle JDK
  action: raw sudo echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
- name: Install Oracle JDK 7
  action: $ansible_pkg_mgr pkg='$item' state=installed
  with_items:
  - oracle-java7-installer
  - oracle-java7-set-default
- name: Ruby | install
  action: $ansible_pkg_mgr pkg='$item' state=installed
  with_items:
  - ruby2.0
  - rubygems
  - ruby-switch
  - ruby2.0-dev
- shell: 'ruby-switch --set ruby2.0'
- name: Ruby | install bundler, rake, foreman
  shell: 'gem install --no-ri --no-rdoc bundler rake foreman'
- name: Nodejs | install
  action: $ansible_pkg_mgr pkg=nodejs state=installed
- name: ENV | zookeepers
  template: src=zookeeper.sh.j2 dest=/etc/profile.d/zookeeper.sh mode=755
