- name: mesos | download
  get_url:
    url: http://downloads.mesosphere.io/master/ubuntu/12.04/mesos_0.14.2_amd64.deb
    dest: /usr/local/mesos_0.14.2_amd64.deb
    sha256sum: da994580accaba5009935a2b74ce9911830a0a111f3bb4c1a97219aedb217280
- name: mesos | install
  command: dpkg --skip-same-version -i /usr/local/{{ item }}
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  with_items: 
    - mesos_0.14.2_amd64.deb
- name: mesos | zookeeper config
  template: src=zk.j2 dest=/etc/mesos/zk
- name: mesos | ip address
  template: src=ip.j2 dest=/etc/mesos/ip
- name: mesos | cluster name
  template: src=cluster.j2 dest=/etc/mesos/cluster
- lineinfile: 
    dest: /etc/default/mesos
    regexp: ^IP=
    line: IP=`cat /etc/mesos/ip`
- lineinfile: 
    dest: /etc/default/mesos-master
    regexp: ^CLUSTER=
    line: CLUSTER=`cat /etc/mesos/cluster`
  when: master == true
- name: mesos | wrapper
  template: src=mesos-init-wrapper.j2 dest=/usr/bin/mesos-init-wrapper mode=755
- name: mesos | start master service
  service: name=mesos-master state=started
  when: master == true
- name: mesos | start master service
  service: name=mesos-master state=stopped
  when: master == false
- name: mesos | start slave service
  service: name=mesos-slave state=started
  when: master == false
- name: mesos | start slave service
  service: name=mesos-slave state=stopped
  when: master == true

