---
- apt_repository: repo='ppa:brightbox/ruby-ng' update_cache=true
- apt_repository: repo='ppa:chris-lea/node.js' update_cache=true
- apt: pkg=$item state=latest install_recommends=no
  with_items:
  - build-essential
  - gawk
  - libyaml-dev
  - libffi-dev  
  - libsqlite3-dev
  - sqlite3
- name: Ruby | install
  action: $ansible_pkg_mgr pkg='$item' state=installed
  with_items:
  - ruby2.0
  - rubygems
  - ruby-switch
  - ruby2.0-dev
- shell: 'ruby-switch --set ruby2.0'
- name: Ruby | install bundler, rake, foreman
  shell: 'gem install --no-ri --no-rdoc bundler rake foreman'
- name: Nodejs | install
  action: $ansible_pkg_mgr pkg=nodejs state=installed
