- name: zookeeper registry | present?
  shell: docker images | grep 42195/zookeeper
  register: zookeeper_present
  ignore_errors: true
- name: zookeeper registry | pull 42195/zookeeper
  shell: docker pull 42195/zookeeper
  when: zookeeper_present.stdout.find('zookeeper') == -1
- name: zookeeper | running?
  shell: docker ps | grep 42195/zookeeper
  register: zookeeper_running
  ignore_errors: true
- name: zookeeper | start
  shell: docker run -d -p 5000:5000 42195/zookeeper
  when: zookeeper_running.stdout.find('zookeeper') == -1
