- apt_repository: repo='deb [arch=amd64] http://archive.cloudera.com/cdh4/ubuntu/precise/amd64/cdh precise-cdh4 contrib' state=present update_cache=yes
- apt: pkg=$item state=latest install_recommends=yes force=yes
  with_items:
  - zookeeper
  - zookeeper-server
- name: zookeeper | check dir
  stat: path=/var/lib/zookeeper
  register: check_path
- name: zookeeper | init
  shell: zookeeper-server-initialize
  when: check_path.stat.exists == false
- name: zookeeper | datadir owner
  file: dest=/var/lib/zookeeper mode=774 owner=zookeeper group=zookeeper state=directory recurse=yes
  when: check_path.stat.exists == false
- service: name=zookeeper-server state=started

